import { Providers } from "@/utils/Providers";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import TopNavBar from "@/components/Navbar-component/TopNavBar";
import BottomNavBar from "@/components/Navbar-component/BottomNavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <Providers>
          <div className="children m-5">
            <TopNavBar />
            {children}
            <BottomNavBar />
          </div>
        </Providers>
      </body>
    </html>
  );
}
